# Generated by Django 4.1.3 on 2022-12-03 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("EV", "Everyone"),
                            ("ME", "Only Me"),
                            ("FR", "Friends"),
                        ],
                        default="EV",
                        max_length=2,
                    ),
                ),
                ("title", models.CharField(default="Today's Review", max_length=255)),
                ("text", models.TextField()),
                ("personal_thoughts", models.TextField()),
                ("published", models.BooleanField(default=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
    ]
