# Generated by Django 4.1.3 on 2022-12-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_remove_review_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="personal_thoughts",
            field=models.TextField(blank=True),
        ),
    ]
