# Generated by Django 4.1.3 on 2022-12-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friendship", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendshiprequests",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
